#!/bin/sh /etc/rc.common
# Copyright (C) 2024

START=99
STOP=10

USE_PROCD=1

NAME=fakehttp
PROG=/usr/bin/fakehttp

start_service() {
	config_load fakehttp
	config_get_bool enabled main enabled 0
	[ "$enabled" -eq 1 ] || return 1

	config_get host main host
	config_get iface main iface
	config_get mark main mark
	config_get num main num
	config_get repeat main repeat
	config_get ttl main ttl
	config_get mask main mask

	procd_open_instance
	procd_set_param command /usr/bin/fakehttp

	procd_append_param command -h "$host"
	
	if [ -n "$iface" ]; then
		procd_append_param command -i "$iface"
	fi
	[ -n "$mark" ] && procd_append_param command -m "$mark"
	[ -n "$num" ] && procd_append_param command -n "$num"
	[ -n "$repeat" ] && procd_append_param command -r "$repeat"
	[ -n "$ttl" ] && procd_append_param command -t "$ttl"
	[ -n "$mask" ] && procd_append_param command -x "$mask"
	
	procd_set_param respawn
	procd_set_param stdout 1
	procd_set_param stderr 1
	
	procd_close_instance
}

stop_service() {
	killall fakehttp 2>/dev/null
}

start() {
	start_service
}

stop() {
	stop_service
}

restart() {
	stop_service
	sleep 1
	start_service
} 