#!/bin/sh /etc/rc.common

USE_PROCD=1
START=96
STOP=10

PROG=/usr/sbin/slaac-dns-sync

start_service() {
	local enabled

	config_load slaac_dns_sync
	config_get_bool enabled main enabled 0
	[ "$enabled" -eq 1 ] || return 0

	procd_open_instance
	procd_set_param command "$PROG" --daemon
	procd_set_param respawn 3600 5 5
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param file /etc/config/slaac_dns_sync
	procd_close_instance
}

service_stopped() {
	"$PROG" --cleanup >/dev/null 2>&1
}

service_triggers() {
	procd_add_reload_trigger slaac_dns_sync dhcp
}
